# Generated by Django 4.1.5 on 2023-06-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_art_date_uploaded_alter_art_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image of the work'),
        ),
    ]
