# Generated by Django 4.1.5 on 2023-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_attachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Image of the work'),
        ),
    ]
